{% set name = "birdy" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/birdhouse-{{ name }}/birdhouse_{{ name }}-{{ version }}.tar.gz
  sha256: 10d90a7584d0ef8d355b6114d15937bff4a9c446db3f30be26f5187a9eccdad0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - birdy = birdy.cli.run:cli

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - boltons
    - click
    - funcsigs
    - ipython
    - jinja2
    - lxml
    - owslib >=0.21
    - packaging
    - pyopenssl
    - python-dateutil >=2.8.1
    - requests >=2.0
    - wrapt

test:
  imports:
    - birdy
  requires:
    - pip
    - pytest
    - xarray
  source_files:
    - birdy
    - setup.cfg
    - tests
  commands:
    - pip check
    - pytest -m "not online"

about:
  home: https://github.com/bird-house/birdy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Birdy provides a command-line tool to work with Web Processing Services (WPS).
  description: |
    Birdy is a Python command-line tool to work with Web Processing Services (WPS).
    It is built with the capabilities of OWSLib from the GeoPython project and allows
    for ease in the development of WPS-enabled services as part of the Bird-house ecosystem.
  doc_url: https://birdy.readthedocs.io/en/stable/
  dev_url: https://github.com/bird-house/birdy

extra:
  recipe-maintainers:
    - cehbrecht
    - Zeitsperre
